In [1]:
# import
import tensorflow as tf

In [2]:
#  version
tf.__version__

'2.7.0'

In [3]:
# check GPU availability
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [4]:
# create integer constant
a = tf.constant(10)
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [5]:
# create string constant
sth = tf.constant("First time practicing")
sth

<tf.Tensor: shape=(), dtype=string, numpy=b'First time practicing'>

In [6]:
# create boolean constant
boool = tf.constant(True)
boool

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [9]:
# create constant numpy array / list/ tuple
import numpy as np

np_array = tf.constant(np.array([1,3,5,7]))
np_array

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 3, 5, 7])>

In [12]:
# create 1D array
tensor_1D = tf.constant([1,2,4,5])
tensor_1D

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 4, 5], dtype=int32)>

In [13]:
# 2D array
tensor_2D = tf.constant([[1,2,4,5],[2,6,8,9]])
tensor_2D

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 4, 5],
       [2, 6, 8, 9]], dtype=int32)>

In [16]:
# from 1D to 2D
tensor_1D_to_2D = tf.constant([1,2,3,4,5,6], shape=(2,3), dtype="float32")
tensor_1D_to_2D

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [17]:
# create multidimention
tensor_3D = tf.constant([[[1,2],[3,4],[5,6]]])
tensor_3D

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4],
        [5, 6]]], dtype=int32)>

In [18]:
type(tensor_3D)

tensorflow.python.framework.ops.EagerTensor

In [19]:
# shape
tensor_3D.shape

TensorShape([1, 3, 2])

In [20]:
tensor_2D.shape

TensorShape([2, 4])

In [24]:
# access constant value
tensor_1D.numpy()

array([1, 2, 4, 5], dtype=int32)

In [26]:
tensor_2D.dtype

tf.int32

In [27]:
tensor_1D_to_2D.dtype

tf.float32

In [29]:
# what we can't do ?
tf.constant([1,23.5, "Nepal"])

ValueError: Can't convert Python sequence with mixed types to Tensor.

Finished !!!