In [149]:
import tensorflow as tf
import numpy as np

In [150]:
# addition
a = 10
b = 23
a+b

33

In [151]:
tf.add(a,b).numpy()

33

In [152]:
list1 = [2,4,6,8]
list2 = [1,3,5,7]
tf.add(list1,list2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 3,  7, 11, 15], dtype=int32)>

In [153]:
touple1 = [2,4,6,8]
touple2 = [1,3,5,7]
tf.add(touple1,touple2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 3,  7, 11, 15], dtype=int32)>

In [154]:
tf.add(list1,touple2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 3,  7, 11, 15], dtype=int32)>

In [155]:
tf.add(list1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([12, 14, 16, 18], dtype=int32)>

In [156]:
list3 = [1,2,3,4,5]
tf.add(list2,list3)

InvalidArgumentError: Incompatible shapes: [4] vs. [5] [Op:AddV2]

In [ ]:
# add 2 numpy array
npa1 = np.array([1,2,3,4])
npa2 = np.array([1,2,3,4])
tf.add(npa1,npa2)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([2, 4, 6, 8])>

In [ ]:
tf.add(npa1,a)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([11, 12, 13, 14])>

In [ ]:
npa3 = np.array([5])
tf.add(npa1,npa3)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([6, 7, 8, 9])>

In [ ]:
# add 2 constant tensor
tcon1=tf.constant([1,2,3,4])
tcon2=tf.constant([1,2,3,4])

tf.add(tcon1,tcon2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8], dtype=int32)>

In [ ]:
tf.add(tcon1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([11, 12, 13, 14], dtype=int32)>

In [ ]:
# add 2 variable tensor
tvar1=tf.Variable([1,2,3,4])
tvar2=tf.Variable([5,6,7,8])

tf.add(tvar1,tvar2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12], dtype=int32)>

In [ ]:
tf.add(tvar1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([11, 12, 13, 14], dtype=int32)>

In [ ]:
# adding variable and constant
tf.add(tcon1,tvar1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8], dtype=int32)>

Addition Finished

In [ ]:
b-a

13

In [ ]:
tf.subtract(b,a)

<tf.Tensor: shape=(), dtype=int32, numpy=13>

In [ ]:
tf.subtract(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=-13>

In [ ]:
tf.subtract(list1,list2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 1, 1, 1], dtype=int32)>

In [ ]:
tf.subtract(list1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-8, -6, -4, -2], dtype=int32)>

In [ ]:
tf.subtract(list1,list3)

InvalidArgumentError: Incompatible shapes: [4] vs. [5] [Op:Sub]

In [ ]:
tf.subtract(touple1,touple2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 1, 1, 1], dtype=int32)>

In [ ]:
tf.subtract(touple1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-8, -6, -4, -2], dtype=int32)>

In [ ]:
tf.subtract(tcon1,tcon2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 0, 0, 0], dtype=int32)>

In [ ]:
tf.subtract(tcon1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-9, -8, -7, -6], dtype=int32)>

In [ ]:
tf.subtract(tvar1,tvar2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-4, -4, -4, -4], dtype=int32)>

In [ ]:
tf.subtract(tvar1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-9, -8, -7, -6], dtype=int32)>

In [ ]:
tf.subtract(npa1,npa2)


<tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 0, 0, 0])>

In [ ]:
tf.subtract(npa1,a)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([-9, -8, -7, -6])>

In [ ]:
tf.subtract(npa1,npa3)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([-4, -3, -2, -1])>

Subtract Finished

In [ ]:
a*b

230

In [ ]:
tf.multiply(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=230>

In [ ]:
tf.multiply(list1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([20, 40, 60, 80], dtype=int32)>

In [ ]:
tf.multiply(list1,list2)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 2, 12, 30, 56], dtype=int32)>

In [ ]:
tf.multiply(list1,list3)


InvalidArgumentError: Incompatible shapes: [4] vs. [5] [Op:Mul]

In [ ]:
tf.multiply(touple1,touple2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 2, 12, 30, 56], dtype=int32)>

In [ ]:
tf.multiply(touple1,b)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 46,  92, 138, 184], dtype=int32)>

In [ ]:
tf.multiply(tcon1,tcon2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

In [ ]:
tf.multiply(tcon1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 20, 30, 40], dtype=int32)>

In [ ]:
tf.multiply(tvar1,tvar2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5, 12, 21, 32], dtype=int32)>

In [ ]:
tf.multiply(tvar1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 20, 30, 40], dtype=int32)>

In [ ]:
tf.multiply(npa1,npa2)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 1,  4,  9, 16])>

In [ ]:
tf.multiply(npa2,b)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([23, 46, 69, 92])>

In [ ]:
x = np.ones(6).reshape(1,2,1,3)
x

array([[[[1., 1., 1.]],

        [[1., 1., 1.]]]])

In [ ]:
y = np.ones(6).reshape(2,1,3,1)
y

array([[[[1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.]]]])

In [ ]:
tf.multiply(x,y).numpy()

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

Multiply Finished

In [ ]:
a/b

0.43478260869565216

In [ ]:
tf.divide(a,b)

<tf.Tensor: shape=(), dtype=float64, numpy=0.43478260869565216>

In [ ]:
tf.divide(list1,list2)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([2.        , 1.33333333, 1.2       , 1.14285714])>

In [ ]:
tf.divide(list1,a)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.2, 0.4, 0.6, 0.8])>

In [ ]:
tf.divide(a,list1)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([5.        , 2.5       , 1.66666667, 1.25      ])>

In [ ]:
tf.divide(touple1,touple2)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([2.        , 1.33333333, 1.2       , 1.14285714])>

In [ ]:
tf.divide(touple1,a)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.2, 0.4, 0.6, 0.8])>

In [ ]:
tf.divide(touple1,list1)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 1., 1., 1.])>

In [ ]:
tf.divide(tcon1,tcon2)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 1., 1., 1.])>

In [ ]:
tf.divide(tcon1,a)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.1, 0.2, 0.3, 0.4])>

In [ ]:
tf.divide(tvar1,tvar2)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.2       , 0.33333333, 0.42857143, 0.5       ])>

In [ ]:
tf.divide(tcon1,tvar1)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 1., 1., 1.])>

In [ ]:
tf.divide(a,tvar1)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([10.        ,  5.        ,  3.33333333,  2.5       ])>

In [ ]:
tf.divide(npa1,npa2)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 1., 1., 1.])>

In [ ]:
tf.divide(npa1,npa3)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.2, 0.4, 0.6, 0.8])>

In [ ]:
tf.divide(x,y).numpy()

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

Divide Finished

In [ ]:
# sqrt function 
# It calcumate element wise square root of numpy array and tensorflow tensor

In [ ]:
s = 16.0
tf.sqrt(s)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [ ]:
newList1 = [4.0, 9.0,16.0, 25.0]
tf.sqrt(newList1)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2., 3., 4., 5.], dtype=float32)>

In [ ]:
newNpa1 = np.array([4,9,25],dtype=np.float32)
tf.sqrt(newNpa1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 5.], dtype=float32)>

In [ ]:
newNpa1.dtype

dtype('float32')

In [ ]:
tf.sqrt(y)

<tf.Tensor: shape=(2, 1, 3, 1), dtype=float64, numpy=
array([[[[1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.]]]])>

In [ ]:
newConTensor = tf.constant([1,4,9],dtype="float32")
tf.sqrt(newConTensor)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [ ]:
newVarTensor = tf.Variable([4,16,9],dtype="float32")
tf.sqrt(newVarTensor)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 4., 3.], dtype=float32)>

Square Root Finished

In [ ]:
p=2
q=3
tf.pow(p,q)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
tf.pow(list1,2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 4, 16, 36, 64], dtype=int32)>

In [ ]:
tf.pow(list1,list2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([      2,      64,    7776, 2097152], dtype=int32)>

In [158]:
tf.pow(list1,list3)

InvalidArgumentError: Incompatible shapes: [4] vs. [5] [Op:Pow]

In [157]:
tf.pow(newNpa1,3)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([   64.,   729., 15625.], dtype=float32)>

In [ ]:
tf.pow(tcon1,3)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  8, 27, 64], dtype=int32)>

In [ ]:
tf.pow(tcon1,tcon2)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([  1,   4,  27, 256], dtype=int32)>

In [ ]:
tf.pow(tvar1,2)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

In [ ]:
tf.pow(npa1,npa3)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([   1,   32,  243, 1024])>

In [ ]:
tf.pow(npa1,npa2)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([  1,   4,  27, 256])>

In [ ]:
tf.pow(x,y).numpy()

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

Power Finished

In [159]:
# maximum value ,element wise comparision garerea out put dinxa
tf.maximum(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=23>

In [160]:
tf.maximum(a,b).numpy()

23

In [162]:
tf.maximum(list1,list2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8], dtype=int32)>

In [173]:
tf.maximum(list1,tcon1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8], dtype=int32)>

In [163]:
tf.maximum(touple1,touple2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8], dtype=int32)>

In [165]:
tf.maximum(list1, a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 10, 10, 10], dtype=int32)>

In [169]:
tf.maximum(newConTensor, a)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([10., 10., 10.], dtype=float32)>

In [170]:
tf.maximum(tcon1, a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 10, 10, 10], dtype=int32)>

In [171]:
tf.maximum(tvar1, tvar2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([5, 6, 7, 8], dtype=int32)>

In [172]:
tf.maximum(a, tvar2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 10, 10, 10], dtype=int32)>

In [166]:
tf.maximum(list1, list3)

InvalidArgumentError: Incompatible shapes: [4] vs. [5] [Op:Maximum]

In [167]:
tf.maximum(npa1,npa2)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [168]:
tf.maximum(npa1,npa3)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([5, 5, 5, 5])>

Maximum finished

In [174]:
tf.minimum(a,b).numpy()

10

In [186]:
tf.minimum(list1,list2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 3, 5, 7], dtype=int32)>

In [187]:
tf.minimum(list1, a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8], dtype=int32)>

In [188]:
tf.minimum(list1, touple1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8], dtype=int32)>

In [189]:
tf.minimum(touple2, touple1)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 3, 5, 7], dtype=int32)>

In [191]:
tf.minimum(a, touple1)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8], dtype=int32)>

In [190]:
tf.minimum(list1, npa1)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [192]:
tf.minimum(list1, list3)


InvalidArgumentError: Incompatible shapes: [4] vs. [5] [Op:Minimum]

In [193]:
tf.minimum(list1, npa3)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 5, 5], dtype=int32)>

In [194]:
tf.minimum(tcon1, tcon2)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [195]:
tf.minimum(tcon1, b)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [196]:
tf.minimum(tvar1,tvar2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [197]:
tf.minimum(tvar1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [198]:
tf.minimum(tvar1,list1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [199]:
tf.minimum(tcon2,npa3)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [201]:
tf.minimum(x,y).numpy()

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

Minimum Finished