In [1]:
import tensorflow as tf

In [6]:
# create a tensor with all elements one
ones2dTensor = tf.ones((2,2),tf.float32)
ones2dTensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [10]:
ones3dTensor = tf.ones((2,2,4),tf.float32)
ones3dTensor

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [11]:
# create a tensor of all ones that has the same shape as the input
const2Dtensor = tf.constant([[1,2,3],[4,5,6]])
tf2D_fromConstTensor =tf.ones_like(const2Dtensor,tf.float32)
tf2D_fromConstTensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [13]:
var2Dtensor = tf.Variable([[1,2,3],[4,5,6]])
tf2D_fromVarTensor = tf.ones_like(var2Dtensor,tf.int32)
tf2D_fromVarTensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [22]:
# ones_initializer : Initializer hat generates tensors initilized to 1
def ones_variable(shape,initilizer):
    return tf.Variable(initilizer(shape= shape))

In [23]:
ones_variable((2,2),tf.ones_initializer())

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [26]:
ones_variable((2,3,6),tf.ones_initializer())


<tf.Variable 'Variable:0' shape=(2, 3, 6) dtype=float32, numpy=
array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]], dtype=float32)>

Finished