In [2]:
# tf.sparse.SparseTensor(indices,value,dense_shape)
import tensorflow as tf

In [5]:
# create tensorflow sparse tensor
st1 = tf.SparseTensor(indices=[[0,3],[2,4]],values=[10,20],dense_shape=[3,10])


In [7]:
print(st1)

SparseTensor(indices=tf.Tensor(
[[0 3]
 [2 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 3 10], shape=(2,), dtype=int64))


In [9]:
# create sparse tensor from Dense
import numpy as np
np_array = np.array([[1,0,0],[0,1,0],[0,0,1]])
np_array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [10]:
sparseTensor = tf.sparse.from_dense(np_array)
sparseTensor

In [11]:
print(sparseTensor)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 1]
 [2 2]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 1 1], shape=(3,), dtype=int64), dense_shape=tf.Tensor([3 3], shape=(2,), dtype=int64))


In [13]:
# extract values , indice and shapes
sparseTensor.values.numpy()

array([1, 1, 1])

In [14]:
sparseTensor.values.numpy().tolist()

[1, 1, 1]

In [17]:
sparseTensor.indices.numpy().tolist()

[[0, 0], [1, 1], [2, 2]]

In [19]:
sparseTensor.dense_shape.numpy().tolist()

[3, 3]

In [21]:
# sparse tensor to dense
denseTensor =tf.sparse.to_dense(sparseTensor)
denseTensor

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])>

In [24]:
denseTensor.numpy()

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [26]:
# mathematical operation on sparse tensor
sparseTAdd = tf.sparse.add(sparseTensor,sparseTensor)
print(sparseTAdd)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 1]
 [2 2]], shape=(3, 2), dtype=int64), values=tf.Tensor([2 2 2], shape=(3,), dtype=int64), dense_shape=tf.Tensor([3 3], shape=(2,), dtype=int64))


In [28]:
tf.sparse.to_dense(sparseTAdd).numpy()

array([[2, 0, 0],
       [0, 2, 0],
       [0, 0, 2]])

Finished !!