In [1]:
import tensorflow as tf

In [2]:
# create variable
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [3]:
a =tf.Variable([1,5,7,9])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 5, 7, 9], dtype=int32)>

In [4]:
a.name

'Variable:0'

In [5]:
a.shape

TensorShape([4])

In [6]:
a.dtype

tf.int32

In [8]:
a.numpy()

array([1, 5, 7, 9], dtype=int32)

In [9]:
type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [12]:
# create tensor using int, float,string, bool, complex_no

tenInt = tf.Variable([1.3,2,3,4])
tenInt

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1.3, 2. , 3. , 4. ], dtype=float32)>

In [13]:
tenStr = tf.Variable("Sujan")
tenStr

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Sujan'>

In [15]:
tenBool = tf.Variable(True)
tenBool

<tf.Variable 'Variable:0' shape=() dtype=bool, numpy=True>

In [19]:
tenCom  = tf.Variable([1+2j])
tenCom

<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([1.+2.j])>

In [20]:
# create variable using tf constant
tenConstant = tf.constant([1,2,3])
tenConstant

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [21]:
tfVariable= tf.Variable(tenConstant)
tfVariable

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [24]:
# variable with different shape
ten_2D =tf.Variable([[1,3],[2,4]],dtype='float32')

ten_2D

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 3.],
       [2., 4.]], dtype=float32)>

In [28]:
# reahaping tensor
tf.reshape(a,(2,2))


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 5],
       [7, 9]], dtype=int32)>

In [30]:
# get index of highest value

tf.argmax(ten_2D)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [31]:
tf.argmax(ten_2D).numpy()

array([1, 1])

In [32]:
# converting as tensor
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 5, 7, 9], dtype=int32)>

In [34]:
a_tensor = tf.convert_to_tensor(a)
a_tensor

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 5, 7, 9], dtype=int32)>

In [36]:
# change /assign a new value to tensor
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 5, 7, 9], dtype=int32)>

In [37]:
a.assign([4,5,6,7])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 5, 6, 7], dtype=int32)>

In [38]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 5, 6, 7], dtype=int32)>

In [39]:
# assign variable with another memory
a.assign_add([4,5,6,7])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 8, 10, 12, 14], dtype=int32)>

In [42]:
# but cant change the shape and dtype
a.assign_add([1,2,3,4,5.3])

TypeError: Cannot convert [1, 2, 3, 4, 5.3] to EagerTensor of dtype int32

Finished
