In [1]:
import tensorflow as tf

In [6]:
# create a tensor witl all he elements set to zero
zero2Dtensor =tf.zeros((2,2), dtype=tf.float32)
zero2Dtensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [8]:
zero2Dtensor.shape

TensorShape([2, 2])

In [10]:
zero2Dtensor.numpy().tolist()

[[0.0, 0.0], [0.0, 0.0]]

In [13]:
#  zeros_like
# create a tensor with all elements set to zero
const2DTensor = tf.constant([1,2,3,4])

tf2D_fromConstTensor = tf.zeros_like(const2DTensor)
const2DTensor.numpy()

array([1, 2, 3, 4], dtype=int32)

In [16]:
var2DTensor = tf.constant([1,5,8,3])

tf2D_fromVarTensor = tf.zeros_like(var2DTensor)
print(const2DTensor.numpy())
print(const2DTensor.shape)

[1 2 3 4]
(4,)


In [27]:
# tf.zeros_initiliazer : initializer that generates tensors to 0;
def zeros_variable(shape,initilizer):
    return tf.Variable(initilizer(shape= shape))

In [28]:
zero_init_var =zeros_variable((3,4),tf.zeros_initializer())
zero_init_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [30]:
zero_init_newvar =zeros_variable((1,2,4),tf.zeros_initializer())
print(zero_init_newvar.numpy())

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [40]:
# doint all these above in single line

print(tf.Variable(tf.zeros_initializer()((2,2,3),dtype=tf.int32)).numpy())

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
